### ISSUE TITLE
Sprint 0

### ISSUE THREAD

**Issue by Alanjoose** [Hederblz/alien-task#1]
- [x]  Configuração do ambiente laravel

- [x] Definição das técnicas de elicitação de requisitos (Escolher pelo menos 2 técnicas de pesquisa)

- [x] Aplicação das técnicas de elicitação de requisitos

- [x]  Criação do modelo de banco de dados (Implementação do modelo lógico e físico)
